export const SET_ERROR = 'SET_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'

export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP'
export const ADMIN_SIGNUP = 'ADMIN_SIGNUP'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGIN = 'LOGIN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

// Customer's actions
export const FETCH_PRODUCTS_BY_CATEGORIES = 'FETCH_PRODUCTS_BY_CATEGORIES'
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const REMOVE_FROM_CART_FAILED = 'REMOVE_FROM_CART_FAILED'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'

export const CHECKOUT = 'CHECKOUT'
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'

export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'

// Admin's actions
export const ADMIN_FETCH_ORDERS = 'ADMIN_FETCH_ORDERS'
